CREATE TABLE "GCG_5512_COO_MNT"(
 "PRODUCT_LINE" CHAR(2),
 "DESCRIPTION" CHAR(100),
 "TARIFF_CODE" CHAR(10),
 "TARRIFF_ADDER" CHAR(2),
 "PREF_CRIT" CHAR(7),
 "PRODUCER" CHAR(8),
 "NET_COST" CHAR(10),
 "COUNTRY" CHAR(10),
 "PART" CHAR(20),
 "LOCATION" CHAR(2));